name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: clariad_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.7.0
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Check code formatting
      run: |
        poetry run black --check .
        poetry run isort --check .

    - name: Lint with ruff
      run: poetry run ruff .

    - name: Type check with mypy
      run: poetry run mypy src tests

    - name: Test with pytest
      run: |
        poetry run pytest --cov=src tests/
      env:
        POSTGRES_CONNECTION_STRING: postgresql://postgres:postgres@localhost:5432/clariad_test
